name: PR Tasks Completed Check
on:
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review, synchronize]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
    - uses: kentaro-m/task-completed-checker-action@v0.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
